name: Test

on: push

jobs:
  test:
    name: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.0.1
      - name: Setup GraalVM environment
        uses: graalvm/setup-graalvm@v1
        with:
          java-version: "21"
          distribution: "graalvm"
          github-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Setup Clojure
        uses: DeLaGuardo/setup-clojure@13.0
        with:
          lein: latest
      - name: Install dependencies
        run: lein deps
      - name: Run tests
        run: |
          lein test
          lein cloverage --no-html --coveralls || true
      - name: Coveralls
        run: curl -F json_file=@./target/coverage/coveralls.json https://coveralls.io/api/v1/jobs
